apiVersion : apps/v1
kind: Deployment
metadata:
  name: testimage 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testimage
  template:
    metadata:
      labels:
        app: testimage 
    spec:
      containers:
        - name: testimage 
          image: epamdiplomaacr.azurecr.io/testimage
          ports:
          - containerPort: 5000