apiVersion : apps/v1
kind: Deployment
metadata:
  name: diplomatest 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diplomatest
  template:
    metadata:
      labels:
        app: diplomatest 
    spec:
      containers:
        - name: diplomatest 
          image: epamdiplomaacr.azurecr.io/diplomatest
          ports:
          - containerPort: 5000